spring:
  application:
    name: WorkFlow
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  profiles:
#    active: dev